import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Navbar from "@/components/self-made/dock";
import ThemeToggle from "@/components/self-made/themetoggle";
import { AppWindow } from "lucide-react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Adrij Portfolio",
  description: "Generated by Mr. Adrij Bhadra",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class">
          <div className="fixed top-4 left-4 z-10 flex items-center text-sm">
            <AppWindow className="w-6 h-6 mr-2" />
            Full Stack Developer
          </div>
          <div className="fixed top-4 right-4 z-10">
            <ThemeToggle />
          </div>
          {children}
          <Navbar />
        </ThemeProvider>
      </body>
    </html>
  );
}
